variables:
  aseApiKeyId: SPLO8Z5TXURGNY91LAY80SRSOLINMHJ9
  aseApiKeySecret: K2QNNVLE61QWQCZ0GYEKIU6D4FLYI1YT
  compiledArtifactFolder: none
  scanConfig: Normal scan
  aseAppName: idone
  aseHostname: win-6isoi82juhn
  aseToken: C:\ProgramData\HCL\AppScanSource\config\ounceautod.token
  sevSecGw: highIssues
  maxIssuesAllowed: 100
  WorkingDirectory: $(System.DefaultWorkingDirectory)
  BuildNumber: $(Build.BuildNumber)

trigger: none

pool: alexpipeline

steps:
- pwsh: |
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-AzureDevOps-Integration/main/scripts/appscanase_create_application_ase.ps1 -OutFile appscanase_create_application_ase.ps1
    .\appscanase_create_application_ase.ps1
  displayName: 'Checking Application ID in ASE'
- pwsh: |
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-AzureDevOps-Integration/main/scripts/appscansrc_create_config_scan_folder.ps1 -OutFile appscansrc_create_config_scan_folder.ps1
    .\appscansrc_create_config_scan_folder.ps1
  displayName: 'Creating AppScan Source Config file'
- pwsh: |
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-AzureDevOps-Integration/main/scripts/appscansrc_scan.ps1 -OutFile appscansrc_scan.ps1
    .\appscansrc_scan.ps1
  displayName: 'Running SAST scan'
- pwsh: |
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-AzureDevOps-Integration/main/scripts/appscansrc_publish_assessment_to_enterprise.ps1 -OutFile appscansrc_publish_assessment_to_enterprise.ps1
    .\appscansrc_publish_assessment_to_enterprise.ps1
  displayName: 'Publishing Result Scan into ASE'
- pwsh: |
    Invoke-WebRequest -Uri https://raw.githubusercontent.com/jrocia/AppScanSRC-and-AzureDevOps-Integration/main/scripts/appscansrc_check_security_gate.ps1 -OutFile appscansrc_check_security_gate.ps1
    .\appscansrc_check_security_gate.ps1
  displayName: 'Checking Security Gate'
- publish: $(aseAppName)-$(BuildNumber).pdf
  artifact: $(aseAppName)-$(BuildNumber).pdf
  continueOnError: On
  displayName: 'Uploading PDF to Azure Artifacts'