# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: alexpipeline 

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  asocKey: '6c4d68db-ce1c-bbd7-9fea-da9c1ce4b5d0'
  asocSecret: 'bVu/ciKpTzUTDTG1mys1y1JNES3GfA1BsDSvzwt2Xe4='
  appId: '57bd6a13-a5f7-49e2-8617-b14e20877078'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- powershell: |
    appscan prepare
  displayName: 'Step 1 - Building artifact'
  

- powershell: |
    appscan api_login -u $(asocKey) -P $(asocSecret) -persist
  displayName: 'Step 2 - Login'

- powershell: | 
    echo "Using: "
    echo $(appId) 
    echo $(asocKey) 
    echo $(asocSecret)
    appscan queue_analysis -a $(appId) -n AzurePipelineScanOnDotNet
  displayName: 'Step 3 - Upload and queue scan'
